package celjit

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"

	"github.com/google/cel-go/cel"
	"github.com/nicholasngai/cel-jit/runtime"
)

// EnvConfig configures the construction of an [Env].
type EnvConfig struct {
	// The types available to the runtime.
	Types []reflect.Type

	// The functions in the environment, keyed by their ID. Function IDs should
	// be lower_snake_case and unique.
	Functions map[string]Function
}

// Function is a definition of a function in CEL. A function in CEL may have
// several overloads (e.g. different parameters).
type Function struct {
	// The overloads of the function, keyed by their name. This name is used to
	// define the function or method name (e.g. startsWith).
	Overloads map[string]FunctionOverload
}

// FunctionOverload is a single overload of a [Function]. An overload contains a
// set of type parameters, a return type, and an implementation.
type FunctionOverload struct {
	// True if this is a member overload/method. False if this is a global
	// function.
	IsMemberOverload bool

	// The parameter types to the function. If this is a member overload, the
	// first parameter is the receiver.
	ParameterTypes []*cel.Type

	// The return type of the function.
	ReturnType *cel.Type

	// Implementation must be one of the two following types:
	//
	// - func(a T, b U[, ...]) R
	// - func(a T, b U[, ...]) (R, error)
	//
	// These type mappings are the same as [Compile].
	Implementation any
}

// Env represents a runtime environment for CEL. Like
// [github.com/cel-expr/cel-go/cel.Env], it contains definitions for functions
// that exist at runtime as well as type definitions. Unlike
// [github.com/cel-expr/cel-go/cel.Env], this only supports native types whose
// shape can be read via reflection.
type Env struct {
	config EnvConfig

	runtimeDir string
}

func NewEnv(config EnvConfig) (*Env, error) {
	runtimeDir, err := writeRuntime()
	if err != nil {
		return nil, fmt.Errorf("write runtime: %w", err)
	}

	return &Env{
		config:     config,
		runtimeDir: runtimeDir,
	}, nil
}

func writeRuntime() (_ string, retErr error) {
	// Make runtime dir.
	dir, err := os.MkdirTemp("", "cel-jit-runtime-source-*")
	if err != nil {
		return "", fmt.Errorf("mkdir temp: %w", err)
	}
	defer func() {
		if retErr != nil {
			os.RemoveAll(dir)
		}
	}()

	// Write Go module file.
	if err := writeFilef(filepath.Join(dir, "go.mod"),
		`module github.com/nicholasngai/cel-jit/runtime-source

go 1.26.0
`); err != nil {
		return "", err
	}

	// Write the runtime to it.
	if err := fs.WalkDir(runtime.Source, ".", func(runtimePath string, dirEntry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if dirEntry.IsDir() {
			if err := os.Mkdir(filepath.Join(dir, "runtime", runtimePath), 0o755); err != nil {
				return fmt.Errorf("mkdir %s: %w", filepath.Join(dir, "runtime", runtimePath), err)
			}
		} else {
			contents, err := runtime.Source.ReadFile(runtimePath)
			if err != nil {
				return fmt.Errorf("read embedded %s: %w", runtimePath, err)
			}
			if err := writeFilef(filepath.Join(dir, "runtime", runtimePath), "%s", string(contents)); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return "", err
	}

	return dir, nil
}

// Cleanup removes all filesystem artifacts generated by the environment.
func (e *Env) Cleanup() error {
	if err := os.RemoveAll(e.runtimeDir); err != nil {
		return err
	}
	return nil
}
