package celjit

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sync"

	"github.com/nicholasngai/cel-jit/runtime"
)

var runtimeDir string

var writeRuntime = sync.OnceValues(func() (string, error) {
	// Make runtime dir.
	dir, err := os.MkdirTemp("", "cel-jit-runtime-source-*")
	if err != nil {
		return "", fmt.Errorf("mkdir temp: %w", err)
	}

	// Write Go module file.
	if err := writeFilef(filepath.Join(dir, "go.mod"),
		`module github.com/nicholasngai/cel-jit/runtime-source

go 1.26.0
`); err != nil {
		return "", err
	}

	// Write the runtime to it.
	if err := fs.WalkDir(runtime.Source, ".", func(runtimePath string, dirEntry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if dirEntry.IsDir() {
			if err := os.Mkdir(filepath.Join(dir, "runtime", runtimePath), 0o755); err != nil {
				return fmt.Errorf("mkdir %s: %w", filepath.Join(dir, "runtime", runtimePath), err)
			}
		} else {
			contents, err := runtime.Source.ReadFile(runtimePath)
			if err != nil {
				return fmt.Errorf("read embedded %s: %w", runtimePath, err)
			}
			if err := writeFilef(filepath.Join(dir, "runtime", runtimePath), "%s", string(contents)); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return "", err
	}

	runtimeDir = dir

	return dir, nil
})

// Cleanup removes all filesystem artifacts generated by cel-jit.
func Cleanup() error {
	if runtimeDir != "" {
		if err := os.RemoveAll(runtimeDir); err != nil {
			return err
		}
	}
	return nil
}
