package celjit

import (
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"github.com/nicholasngai/cel-jit/runtime"
)

var runtimeDir string

var writeRuntime = sync.OnceValues(func() (string, error) {
	// Make runtime dir.
	dir, err := os.MkdirTemp("", "cel-jit-runtime-source-*")
	if err != nil {
		return "", fmt.Errorf("mkdir temp: %w", err)
	}

	// Write Go module file.
	if err := writeFile(filepath.Join(dir, "go.mod"),
`module github.com/nicholasngai/cel-jit/runtime-source/runtime

go 1.26.0
`); err != nil {
		return "", err
	}

	// Write the runtime to it.
	if err := os.MkdirAll(filepath.Join(dir, "runtime"), 0o755); err != nil {
		return "", fmt.Errorf("mkdir runtime: %w", err)
	}
	if err := writeFile(filepath.Join(dir, "runtime.go"), runtime.Source); err != nil {
		return "", err
	}

	runtimeDir = dir

	return dir, nil
})

// Cleanup removes all filesystem artifacts generated by cel-jit.
func Cleanup() error {
	if runtimeDir != "" {
		if err := os.RemoveAll(runtimeDir); err != nil {
			return err
		}
	}
	return nil
}
